### ISSUE TITLE
Gotta fill in those vulnerabilities!

### ISSUE THREAD

**Issue by marcusstenbeck** [juxtinteractive/howmuchcoffee#1]
Hey it makes sense that we keep this sought after project alive, eh?

@igierard @jessefulton 

;)

**Comment by jessefulton** [comment]
![screen shot 2018-09-20 at 11 52 05 am](https://user-images.githubusercontent.com/40847/45840366-a789a980-bccb-11e8-9649-a1e554dca79c.jpg)

It's always jQuery...

**Comment by marcusstenbeck** [comment]
Heyyy! @jessefulton what's up?

**Comment by jessefulton** [comment]
Hahah hey! Just getting caught up on my extremely outdated github notifications :). How goes it? Let's chat in github issues!

**Comment by marcusstenbeck** [comment]
All good, all good. I'm just about to branch out and start my own little business. Are you still kicking back in SF?
